#!/usr/bin/with-contenv bash


UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"
export HOME=/channels-dvr
if [ ! -f /channels-dvr/latest/channels-dvr ]; then
  echo "Channels DVR is missing! Downloading it!"
  cd /
  curl -f -s https://getchannels.com/dvr/setup.sh | DOWNLOAD_ONLY=1 sh
  usermod -d /channels-dvr abc
  chown -R abc:abc /channels-dvr
fi
echo "Verifying binary permissions are correct."
chmod +x /channels-dvr/latest/channels-dvr
chmod +x /channels-dvr/latest/comskip
chmod +x /channels-dvr/latest/ffmpeg
chmod +x /channels-dvr/latest/ffmpeg-dl
chmod +x /channels-dvr/latest/ffprobe
echo "Running Channels DVR"
exec \
  s6-setuidgid abc /bin/bash -c \
  'cd /channels-dvr/data && ../latest/channels-dvr >> channels-dvr.log 2>&1'
